### ISSUE TITLE
Is it possible to add a inputs parameter to allow people to customize the content of git commit?

### ISSUE THREAD

**Issue by zhengpq** [cpina/github-action-push-to-another-repository#11]
hello Cpina!  Just like the question says, sometimes i want to add some content to the git commit, maybe like this:

```
- name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'output'
          destination-github-username: 'cpina'
          destination-repository-name: 'push-to-another-repository-output'
          user-email: carles3@pina.cat
          commit-content: 'an example'
```
Is it possible to add this?

Thanks !
