### ISSUE TITLE
Variable in commit-message ?

### ISSUE THREAD

**Issue by tomtom94** [cpina/github-action-push-to-another-repository#22]
Hey would it be possible to make

```
      - name: Push to the repository which will create the staticfiles pod into the cluster
        uses: cpina/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.REPO_ACCESS_TOKEN }}
        with:
          source-directory: 'staticfiles_pod'
          destination-github-username: 'xxxx'
          destination-repository-name: 'staticfiles'
          user-email: xxxx@gmail.com
          commit-message: "new front static files"
          commit-message: "#patch new front static files generated ${GITHUB_REF##*/}"
```
