### ISSUE TITLE
cp: can't stat 'examples/chronoblog-netlify-cms/*': No such file or directory

### ISSUE THREAD

**Issue by Ganevru** [cpina/github-action-push-to-another-repository#24]
Hey! Thanks for this project.

Perhaps I don't understand something, but I get an error:

`cp: can't stat 'examples/chronoblog-netlify-cms/.': No such file or directory`

when launching an action.

Here is the complete code of the yml file:

```
name: Publication of Starters

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Push directory to another repository
        uses: cpina/github-action-push-to-another-repository@v1.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: "examples/chronoblog-netlify-cms"
          destination-github-username: "Chronoblog"
          destination-repository-name: "gatsby-starter-chronoblog-netlify-cms"
          user-email: 8168280+Ganevru@users.noreply.github.com
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
```

Yes, this is an open source project, here is the entire mono repository from which I'm trying to copy some of the files: https://github.com/Chronoblog/gatsby-theme-chronoblog/tree/test-workflows

And this is the repository where I'm trying to copy the "examples/chronoblog-netlify-cms" folder: https://github.com/Chronoblog/gatsby-starter-chronoblog-netlify-cms

Maybe the problem is that I'm using the name of the organization? (Chronoblog)
