### ISSUE TITLE
Support MacOS

### ISSUE THREAD

**Issue by YevhenHerasymenko** [cpina/github-action-push-to-another-repository#36]
I tried to run your action on macOS machine but got error:
Error: Container action is only supported on Linux

Can you add support for macOS

**Comment by cpina** [comment]
Do you have a link to the repository with the logs for this?

**Comment by Ismoh** [comment]
Maybe this helps:

```
jobs:
  build:
    runs-on: macos-latest # use ubuntu-latest here and it works fine
    [...]
    - name: whatever you named it
    uses: cpina/github-action-push-to-another-repository@main
    env:
      API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
    with:
      [...]
```

![image](https://user-images.githubusercontent.com/12631485/161152281-a4fdb99b-aedb-4546-ac06-ed7506d7291f.png)


macos-latest doesn't work for me as well, but ubuntu-latest works fine.
As long as you are able to change this @YevhenHerasymenko , it might help.
