### ISSUE TITLE
ls: <file path>: No such file or directory

### ISSUE THREAD

**Issue by LanKuDot** [cpina/github-action-push-to-another-repository#45]
Hi, I tried to use this action to push the output directory of the Jekyll builder to another repository.
But the actions failed when this action tried to list the content of the output directory.

Here is the setup:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SITE_DIRECTORY: ${{ github.workspace }}/_site
    steps:
      - uses: actions/checkout@v2
      - name: Build the jekyll site
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll \
          -v ${{ env.SITE_DIRECTORY }}:/srv/jekyll/_site \
          jekyll/builder:latest \
          /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
      - name: List site directory
        run: ls ${{ env.SITE_DIRECTORY }}
      - name: Deploy to the github page repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: ${{ env.SITE_DIRECTORY }}
          destination-github-username: LanKuDot
          destination-repository-name: lankudot.github.io
          user-email: <email>
          target-branch: main
```

I inserted a step to list the content of the directory, and it did.

```
> Run ls /home/runner/work/blog-source/blog-source/_site
assets
blog
categories
feed.xml
index.html
posts
robots.txt
sitemap.xml
tags
```

And the message of the action is:

```
Cloning into '/tmp/tmp.LfoiJn'...
ls: /home/runner/work/blog-source/blog-source/_site: No such file or directory
[+] Action start
[+] Cloning destination git repository lankudot.github.io
total 16
drwx------    3 root     root          4096 Nov 15 03:08 .
drwxrwxrwt    1 root     root          4096 Nov 15 03:08 ..
drwxr-xr-x    8 root     root          4096 Nov 15 03:08 .git
-rw-r--r--    1 root     root            52 Nov 15 03:08 README.md
[+] List contents of /home/runner/work/blog-source/blog-source/_site
```

Did I missed something? Thanks!
