### ISSUE TITLE
Erroring with API_TOKEN_GITHUB as empty even though it's set

### ISSUE THREAD

**Issue by ddm999** [cpina/github-action-push-to-another-repository#72]
After ab68811, I'm now getting

> Error: API_TOKEN_GITHUB and SSH_DEPLOY_KEY are empty. Please fill one (recommended the SSH_DEPLOY_KEY

on all my runs, despite API_TOKEN_GITHUB being set in the workflow:

```
 uses: cpina/github-action-push-to-another-repository@main
 env:
   API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
 with:
```

(and yes, the secret is set.)

This worked prior to the update, so it's definitely not a config issue on my end.

https://github.com/cpina/github-action-push-to-another-repository/blob/ab68811c3a865abed38689b4536ba8613a0914d6/entrypoint.sh#L46

It's this check which is failing for whatever reason.
(Also, even if that check worked, the command you're setting there to be run doesn't actually have the token in. You probably want to split the "redacted for display" and "actually used" strings into two different variables.)
